name: Renovate
on:
  workflow_dispatch:
  issues:
    types:
      - edited
  pull_request:
    types:
      - closed

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_WORKFLOW_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
